<?php
/**
 * @copyright since 17:46 14/12/2017
 * @author <mc@dancis.info>
 */
namespace app\common\model;

use McDanci\ThinkPHP\Config;
use think\Model;
use traits\model\SoftDelete;

class Reg extends Model
{
    use SoftDelete;

    protected
        $autoWriteTimestamp = 'datetime',
        $createTime = 'created',
        $updateTime = false,
        $deleteTime = 'deleted';

    protected $readonly = [
        'created',

        'type',
        'name_first',
        'name_last',
        'gender',
        'email',
        'tel',
        'tel_cell',
        'company',
        'street',
        'city',
        'state',
        'zip',
        'iso3166',
        'website',
        'cat',
        'password',
    ];

    /**
     * @todo
     */
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Config::set('');
    }

    /**
     * @todo
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    //region Relation

    public function regExhibitor()
    {
        return $this->hasOne('RegExhibitor')->bind([
            'c_opf',
            'mpt',
            'npe',
            'mc',
            'tse',
        ]);
    }

    public function regVisitor()
    {
        return $this->hasOne('RegVisitor')->bind([
            'job_function',
            'brand',
            'f_man',
        ]);
    }

    //endregion

    /**
     * @param $id
     * @todo
     */
    public function auditPass($id)
    {
        //self::destroy('');
        //self::delete('');
    }
}
