<?php
/**
 * @copyright since 17:46 14/12/2017
 * @author <mc@dancis.info>
 */
namespace app\common\model;

use McDanci\ThinkPHP\Config;
use think\Model;
use traits\model\SoftDelete;

class Reg extends Model
{
    use SoftDelete;

    //region Configuration

    protected
        $autoWriteTimestamp = 'datetime',
        $createTime = 'created',
        $updateTime = false,
        $deleteTime = 'deleted';

    protected $readonly = [
        'created',

        'type',
        'name_first',
        'name_last',
        'gender',
        'email',
        'tel',
        'tel_cell',
        'company',
        'street',
        'city',
        'state',
        'zip',
        'iso3166',
        'website',
        'cat',
        'password',
    ];

    //endregion

    //region Relation

    private static function bindCN($name, $roleType = 1)
    {
        if (in_array($roleType, [1,2])) {
            return ($roleType === 1 ? 'exhibitor' : 'visitor') . '_' . $name;
        }

        return false;
    }

    private static function bindMap(&$bindList, $roleType = 1)
    {
        $bind = [];
        foreach ($bindList as &$bindColumn) {
            $bind[self::bindCN($bindColumn, $roleType)] = $bindColumn;
        }
        $bindList = $bind;
    }

    public function regExhibitor()
    {
        $bindList = [
            'c_opf',
            'mpt',
            'npe',
            'mc',
            'tse',
        ];

        self::bindMap($bindList);
        return $this->hasOne('RegExhibitor')->bind($bindList);
    }

    public function regVisitor()
    {
        $bindList = [
            'job_function',
            'brand',
            'f_man',
        ];

        self::bindMap($bindList, 2);
        return $this->hasOne('RegVisitor')->bind($bindList);
    }

    //endregion

    /**
     * @todo
     */
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Config::set('');
    }

    /**
     * @todo
     */
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $id
     * @todo
     */
    public function auditPass($id)
    {
        //self::destroy('');
        //self::delete('');
    }
}
