#!/usr/bin/env php
<?php
const APP_NAMESPACE = 'application';

const PROJECT_DIR = __DIR__ . DIRECTORY_SEPARATOR;

define('APP_PATH', PROJECT_DIR . APP_NAMESPACE . DIRECTORY_SEPARATOR);

require PROJECT_DIR . 'thinkphp' . DIRECTORY_SEPARATOR . 'console.php';
